# OROBOSA IGHO-OSAGIE
## Assignment 2- Groups 15

In [1]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import time

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("spam\spambase\spambase.data", header=None, sep=",")

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4601 non-null   float64
 1   1       4601 non-null   float64
 2   2       4601 non-null   float64
 3   3       4601 non-null   float64
 4   4       4601 non-null   float64
 5   5       4601 non-null   float64
 6   6       4601 non-null   float64
 7   7       4601 non-null   float64
 8   8       4601 non-null   float64
 9   9       4601 non-null   float64
 10  10      4601 non-null   float64
 11  11      4601 non-null   float64
 12  12      4601 non-null   float64
 13  13      4601 non-null   float64
 14  14      4601 non-null   float64
 15  15      4601 non-null   float64
 16  16      4601 non-null   float64
 17  17      4601 non-null   float64
 18  18      4601 non-null   float64
 19  19      4601 non-null   float64
 20  20      4601 non-null   float64
 21  21      4601 non-null   float64
 22  22      4601 non-null   float64
 23  23      4601 non-null   float64
 24  24      4601 non-null   float64
 25  25      4601 non-null   float64
 26  26      4601 non-null   float64
 27  27      4601 non-null   float64
 28  28      4601 non-null   float64
 29  29      4601 non-null   float64
 30  30      4601 non-null   float64
 31  31      4601 non-null   float64
 32  32      4601 non-null   float64
 33  33      4601 non-null   float64
 34  34      4601 non-null   float64
 35  35      4601 non-null   float64
 36  36      4601 non-null   float64
 37  37      4601 non-null   float64
 38  38      4601 non-null   float64
 39  39      4601 non-null   float64
 40  40      4601 non-null   float64
 41  41      4601 non-null   float64
 42  42      4601 non-null   float64
 43  43      4601 non-null   float64
 44  44      4601 non-null   float64
 45  45      4601 non-null   float64
 46  46      4601 non-null   float64
 47  47      4601 non-null   float64
 48  48      4601 non-null   float64
 49  49      4601 non-null   float64
 50  50      4601 non-null   float64
 51  51      4601 non-null   float64
 52  52      4601 non-null   float64
 53  53      4601 non-null   float64
 54  54      4601 non-null   float64
 55  55      4601 non-null   int64
 56  56      4601 non-null   int64
 57  57      4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

# Model Training and Cross Validation

In [5]:
#split into x and y
X = df.drop(57, axis=1)
Y = df[57]

In [6]:
#define the three models
LR_model = LogisticRegression(max_iter=200)
RF_model = RandomForestClassifier()
SVM_model = SVC()

In [7]:
#LOGISTIC REGRESSION CROSS-VALIDATION

#LR pipeline
LR_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("LR_model", LR_model)
])

LR_trainingTime = []
LR_accuracy = []
LR_f1Scores = []

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)

for train_index, test_index in skf.split(X, Y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    
    start_time = time.time()
    LR_pipeline.fit(X_train, y_train)
    end_time = time.time()
    
    LR_trainingTime.append(end_time - start_time)
    
    y_pred = LR_pipeline.predict(X_test)
    LR_accuracy.append(accuracy_score(y_test, y_pred))
    LR_f1Scores.append(f1_score(y_test, y_pred, average='macro'))

print('\nLogistic Regression')
print("Training times:", [round(x, 3) for x in LR_trainingTime])
print("Accuracy scores:", [round(x, 3) for x in LR_accuracy])
print("F1 scores:", [round(x, 3) for x in LR_f1Scores])

Logistic Regression
Training times: [0.07, 0.027, 0.037, 0.028, 0.035, 0.034, 0.039, 0.041, 0.036, 0.035]
Accuracy scores: [0.92, 0.915, 0.928, 0.939, 0.926, 0.924, 0.926, 0.917, 0.928, 0.937]
F1 scores: [0.914, 0.911, 0.924, 0.936, 0.921, 0.92, 0.922, 0.913, 0.924, 0.934]

In [8]:
#RANDOM FOREST CLASSIFIER CROSS-VALIDATION
RF_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("RF_model", RF_model)
])

RF_trainingTime = []
RF_accuracy = []
RF_f1Scores = []

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=123)

for train_index, test_index in skf.split(X, Y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    
    start_time = time.time()
    RF_pipeline.fit(X_train, y_train)
    end_time = time.time()
    
    RF_trainingTime.append(end_time - start_time)
    
    y_pred = RF_pipeline.predict(X_test)
    RF_accuracy.append(accuracy_score(y_test, y_pred))
    RF_f1Scores.append(f1_score(y_test, y_pred, average='macro'))

print('\nRandom Forest')
print("Training times:", [round(x, 3) for x in RF_trainingTime])
print("Accuracy scores:", [round(x, 3) for x in RF_accuracy])
print("F1 scores:", [round(x, 3) for x in RF_f1Scores])

Random Forest
Training times: [1.468, 1.368, 1.716, 1.544, 1.612, 1.878, 1.624, 1.742, 1.335, 1.536]
Accuracy scores: [0.948, 0.957, 0.963, 0.954, 0.957, 0.946, 0.935, 0.965, 0.957, 0.957]
F1 scores: [0.946, 0.954, 0.961, 0.952, 0.954, 0.943, 0.931, 0.963, 0.954, 0.954]

In [9]:
#SUPPORT VECTOR CLASSIFIER CROSS-VALIDATION
svc_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("SVM_model", SVM_model)
])

svc_trainingTime = []
svc_accuracy = []
svc_f1Scores = []

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=123)

for train_index, test_index in skf.split(X, Y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    
    start_time = time.time()
    svc_pipeline.fit(X_train, y_train)
    end_time = time.time()
    
    svc_trainingTime.append(end_time - start_time)
    
    y_pred = svc_pipeline.predict(X_test)
    svc_accuracy.append(accuracy_score(y_test, y_pred))
    svc_f1Scores.append(f1_score(y_test, y_pred, average='macro'))

print('\nSupport Vector Machine')
print("Training times:", [round(x, 3) for x in svc_trainingTime])
print("Accuracy scores:", [round(x, 3) for x in svc_accuracy])
print("F1 scores:", [round(x, 3) for x in svc_f1Scores])

Support Vector Machine
Training times: [0.427, 0.408, 0.404, 0.398, 0.36, 0.353, 0.35, 0.368, 0.377, 0.348]
Accuracy scores: [0.931, 0.941, 0.935, 0.95, 0.939, 0.902, 0.93, 0.946, 0.933, 0.933]
F1 scores: [0.927, 0.938, 0.932, 0.947, 0.936, 0.897, 0.927, 0.943, 0.929, 0.928]

## Tables for the different measures - Accuracy, Time and F1 Score

In [10]:
#Accuracy Table
accuracy_df = pd.DataFrame({
    'Fold': range(1,11),
    'LR': LR_accuracy,
    'RF': RF_accuracy,
    'SVM': svc_accuracy
})

accuracy_df = accuracy_df.reset_index(drop=True)
avg_row = accuracy_df.mean().rename('Average')
std_row = accuracy_df.std().rename('Std Dev')
avg_row['Fold'] = '_'
std_row['Fold'] = '_'

accuracy_df_stats = pd.concat([accuracy_df, avg_row.to_frame().T, std_row.to_frame().T])

print("=== Accuracy Table ===")
accuracy_df_stats

=== Accuracy Table ===

        Fold        LR        RF       SVM
0          1   0.91974  0.947939  0.930586
1          2  0.915217  0.956522  0.941304
2          3  0.928261  0.963043  0.934783
3          4   0.93913  0.954348      0.95
4          5  0.926087  0.956522   0.93913
5          6  0.923913  0.945652  0.902174
6          7  0.926087  0.934783  0.930435
7          8  0.917391  0.965217  0.945652
8          9  0.928261  0.956522  0.932609
9         10  0.936957  0.956522  0.932609
Average    _  0.926104  0.953707  0.933928
Std Dev    _  0.007721   0.00887  0.012966

In [11]:
#Training Time table
trainingTime_df = pd.DataFrame({
    'Fold': range(1,11),
    'LR': LR_trainingTime,
    'RF': RF_trainingTime,
    'SVM': svc_trainingTime
})

avg_row = trainingTime_df.mean().rename('Average')
std_row = trainingTime_df.std().rename('Std Dev')
avg_row['Fold'] = '_'
std_row['Fold'] = '_'

trainingTime_df_stats = pd.concat([trainingTime_df, avg_row.to_frame().T, std_row.to_frame().T])

print("=== Training Time Table ===")
trainingTime_df_stats

=== Training Time Table ===

        Fold        LR        RF       SVM
0          1  0.070164  1.467705  0.427166
1          2  0.026969   1.36761  0.408091
2          3  0.036615  1.715733  0.403961
3          4  0.028246   1.54403  0.397683
4          5  0.035209  1.612364  0.360371
5          6  0.033558  1.877846   0.35285
6          7  0.039401  1.623659  0.350042
7          8  0.041106  1.741696  0.367681
8          9  0.035656  1.335079  0.377049
9         10  0.035261  1.536328   0.34832
Average    _  0.038218  1.582205  0.379321
Std Dev    _  0.012041  0.169014  0.028048

In [12]:
#F1 Table
F1Scores_df = pd.DataFrame({
    'Fold': range(1,11),
    'LR': LR_f1Scores,
    'RF': RF_f1Scores,
    'SVM': svc_f1Scores
})

avg_row = F1Scores_df.mean().rename('Average')
std_row = F1Scores_df.std().rename('Std Dev')
avg_row['Fold'] = '_'
std_row['Fold'] = '_'

F1Scores_df_stats = pd.concat([F1Scores_df, avg_row.to_frame().T, std_row.to_frame().T])

print("=== F1Score ===")
F1Scores_df_stats

=== F1Score ===

        Fold        LR        RF       SVM
0          1  0.914314  0.945528   0.92723
1          2  0.910557  0.954455  0.938078
2          3  0.923993  0.961469  0.931682
3          4  0.936111  0.952036  0.947252
4          5   0.92125  0.953985  0.935717
5          6  0.919897  0.943231  0.896797
6          7  0.922105  0.931125  0.926534
7          8  0.913464  0.963344  0.942665
8          9  0.924318  0.954273  0.928904
9         10  0.934023  0.953677  0.927947
Average    _  0.922003  0.951312  0.930281
Std Dev    _  0.008306  0.009346  0.013685

In [13]:
#So the three tables are: F1Scores_df, trainingTime_df and accuracy_df - The tables shown above are the stat tables
#Now, I create rank tables to begin the friedman test
#Remember Best (1) to Worst(3). For F1score and accuracy, the higher the better. For Time - the lower the better 

model_cols = ['LR', 'RF', 'SVM']

#Accuracy Rank Table
accuracy_ranks = accuracy_df[model_cols].rank(axis=1, ascending=False)
accuracy_ranks.insert(0, 'Fold', range(1,11)) #adding the fold column
Accuracy_rankMean = accuracy_ranks.mean().rename('Mean')
Accuracy_rankMean['Fold'] = '_'
accuracy_ranks = pd.concat([accuracy_ranks, Accuracy_rankMean.to_frame().T])
print('\n\n ACCURACY RANK TABLE')
print('\n', accuracy_ranks)

#F1 Score Rank Table
f1_ranks = F1Scores_df[model_cols].rank(axis=1, ascending=False)
f1_ranks.insert(0, 'Fold', range(1,11)) #adding the fold column
F1_rankMean = f1_ranks.mean().rename('Mean')
F1_rankMean['Fold'] = '_'
f1_ranks = pd.concat([f1_ranks, F1_rankMean.to_frame().T])
print('\n\n F1SCORE RANK TABLE')
print('\n', f1_ranks)

#Training Time Rank Table
time_ranks = trainingTime_df[model_cols].rank(axis=1, ascending=True)
time_ranks.insert(0, 'Fold', range(1,11)) #adding the fold column
time_rankMean = time_ranks.mean().rename('Mean')
time_rankMean['Fold'] = '_'
time_ranks = pd.concat([time_ranks, time_rankMean.to_frame().T])
print('\n\n TRAINING TIME RANK TABLE')
print('\n', time_ranks)

 ACCURACY RANK TABLE

      Fold   LR   RF  SVM
0       1  3.0  1.0  2.0
1       2  3.0  1.0  2.0
2       3  3.0  1.0  2.0
3       4  3.0  1.0  2.0
4       5  3.0  1.0  2.0
5       6  2.0  1.0  3.0
6       7  3.0  1.0  2.0
7       8  3.0  1.0  2.0
8       9  3.0  1.0  2.0
9      10  2.0  1.0  3.0
Mean    _  2.8  1.0  2.2


 F1SCORE RANK TABLE

      Fold   LR   RF  SVM
0       1  3.0  1.0  2.0
1       2  3.0  1.0  2.0
2       3  3.0  1.0  2.0
3       4  3.0  1.0  2.0
4       5  3.0  1.0  2.0
5       6  2.0  1.0  3.0
6       7  3.0  1.0  2.0
7       8  3.0  1.0  2.0
8       9  3.0  1.0  2.0
9      10  2.0  1.0  3.0
Mean    _  2.8  1.0  2.2


 TRAINING TIME RANK TABLE

      Fold   LR   RF  SVM
0       1  1.0  3.0  2.0
1       2  1.0  3.0  2.0
2       3  1.0  3.0  2.0
3       4  1.0  3.0  2.0
4       5  1.0  3.0  2.0
5       6  1.0  3.0  2.0
6       7  1.0  3.0  2.0
7       8  1.0  3.0  2.0
8       9  1.0  3.0  2.0
9      10  1.0  3.0  2.0
Mean    _  1.0  3.0  2.0

# Friedman Test

In [14]:
#So the three tables are: F1Scores_df, trainingTime_df and accuracy_df - The tables shown above are the stat tables
#Now, I create rank tables to begin the friedman test
#Remember Best (1) to Worst(3). For F1score and accuracy, the higher the better. For Time - the lower the better 

model_cols = ['LR', 'RF', 'SVM'] #apparently i cant just pass the exact values into the next line, I must use this variable

### Creating the rank tables for each metric

In [15]:
#Accuracy Rank Table
accuracy_ranks = accuracy_df[model_cols].rank(axis=1, ascending=False)
accuracy_ranks.insert(0, 'Fold', range(1,11)) #adding the fold column
Accuracy_rankMean = accuracy_ranks.mean().rename('Mean')
Accuracy_rankMean['Fold'] = '_'
accuracy_ranks = pd.concat([accuracy_ranks, Accuracy_rankMean.to_frame().T])
print('\n\n ACCURACY RANK TABLE')
print('\n', accuracy_ranks)

#F1 Score Rank Table
f1_ranks = F1Scores_df[model_cols].rank(axis=1, ascending=False)
f1_ranks.insert(0, 'Fold', range(1,11)) #adding the fold column
F1_rankMean = f1_ranks.mean().rename('Mean')
F1_rankMean['Fold'] = '_'
f1_ranks = pd.concat([f1_ranks, F1_rankMean.to_frame().T])
print('\n\n F1SCORE RANK TABLE')
print('\n', f1_ranks)

#Training Time Rank Table
time_ranks = trainingTime_df[model_cols].rank(axis=1, ascending=True)
time_ranks.insert(0, 'Fold', range(1,11)) #adding the fold column
time_rankMean = time_ranks.mean().rename('Mean')
time_rankMean['Fold'] = '_'
time_ranks = pd.concat([time_ranks, time_rankMean.to_frame().T])
print('\n\n TRAINING TIME RANK TABLE')
print('\n', time_ranks)

 ACCURACY RANK TABLE

      Fold   LR   RF  SVM
0       1  3.0  1.0  2.0
1       2  3.0  1.0  2.0
2       3  3.0  1.0  2.0
3       4  3.0  1.0  2.0
4       5  3.0  1.0  2.0
5       6  2.0  1.0  3.0
6       7  3.0  1.0  2.0
7       8  3.0  1.0  2.0
8       9  3.0  1.0  2.0
9      10  2.0  1.0  3.0
Mean    _  2.8  1.0  2.2


 F1SCORE RANK TABLE

      Fold   LR   RF  SVM
0       1  3.0  1.0  2.0
1       2  3.0  1.0  2.0
2       3  3.0  1.0  2.0
3       4  3.0  1.0  2.0
4       5  3.0  1.0  2.0
5       6  2.0  1.0  3.0
6       7  3.0  1.0  2.0
7       8  3.0  1.0  2.0
8       9  3.0  1.0  2.0
9      10  2.0  1.0  3.0
Mean    _  2.8  1.0  2.2


 TRAINING TIME RANK TABLE

      Fold   LR   RF  SVM
0       1  1.0  3.0  2.0
1       2  1.0  3.0  2.0
2       3  1.0  3.0  2.0
3       4  1.0  3.0  2.0
4       5  1.0  3.0  2.0
5       6  1.0  3.0  2.0
6       7  1.0  3.0  2.0
7       8  1.0  3.0  2.0
8       9  1.0  3.0  2.0
9      10  1.0  3.0  2.0
Mean    _  1.0  3.0  2.0

### The Friedman Test for Accuracy

In [16]:
#Friedman Numerator = n * (Rank_meanLR -2)^2 + (Rank_meanRF -2)^2 + (Rank_meanSVM)^2
#Denominator = (sum of Individual deviation from the R_bar)^2 / n * (k-1)

#I'll use a table to calculate the individual deviation
print(f"The average for the Accuracy of each algorithm: {Accuracy_rankMean}")

The average for the Accuracy of each algorithm: Fold      _
LR      2.8
RF      1.0
SVM     2.2
Name: Mean, dtype: object

In [17]:
#Caluclating the Numerator
n = 10
k = 3
R_bar = 2
Acc_numerator = (((Accuracy_rankMean['LR'] - R_bar)**2) + ((Accuracy_rankMean['RF']-R_bar)**2) + ((Accuracy_rankMean['SVM']-R_bar)**2)) * n
print('Accuracy Numerator = ', Acc_numerator)

Accuracy Numerator =  16.799999999999997

In [18]:
#Calculating the Denominator - Accuracy
RmeanDev_table = (accuracy_ranks[model_cols] - R_bar)**2 #Calculating R - R_BAR for each cell
RmeanDev_table.drop(index= 'Mean', inplace=True, axis=0)
RmeanDev_table.insert(0, 'Fold', range(1,11)) #adding the fold column
Rmean_sum = RmeanDev_table.sum().rename('Sum')
Rmean_sum['Fold'] = '_'
RmeanDev_table = pd.concat([RmeanDev_table, Rmean_sum.to_frame().T])
print('\n\n Accuracy Squared Deviation Table')
print('\n', RmeanDev_table)

Acc_denominator = (Rmean_sum['LR'] + Rmean_sum['RF'] + Rmean_sum['SVM']) / (n *(k-1))
print('\n Accuracy Denominator = ', Acc_denominator)

 Accuracy Squared Deviation Table

     Fold   LR    RF  SVM
0      1  1.0   1.0  0.0
1      2  1.0   1.0  0.0
2      3  1.0   1.0  0.0
3      4  1.0   1.0  0.0
4      5  1.0   1.0  0.0
5      6  0.0   1.0  1.0
6      7  1.0   1.0  0.0
7      8  1.0   1.0  0.0
8      9  1.0   1.0  0.0
9     10  0.0   1.0  1.0
Sum    _  8.0  10.0  2.0

 Accuracy Denominator =  1.0

In [19]:
#The final equation - For Accuracy
Acc_Fried = Acc_numerator / Acc_denominator
print(f"Friedman Statistic for Accuracy: {Acc_Fried:.2f}")

Friedman Statistic for Accuracy: 16.80

### The Friedman Test for F1 Score

In [20]:
print(f"The average score for the F1 Measure of each algorithm: {F1_rankMean}")

The average score for the F1 Measure of each algorithm: Fold      _
LR      2.8
RF      1.0
SVM     2.2
Name: Mean, dtype: object

In [21]:
#Calculating the Numerator - F1 Score
f1_numerator = n * (((F1_rankMean['LR'] - R_bar)**2) + ((F1_rankMean['RF']-R_bar)**2) + ((F1_rankMean['SVM']-R_bar)**2))
print(f"F1 Numerator: {f1_numerator:.2f}")

F1 Numerator: 16.80

In [22]:
#Calculating the Denominator - F1 Score
f1_Rbar_Dev = (f1_ranks[model_cols] - R_bar)**2 #Calculating R - R_BAR for each cell
f1_Rbar_Dev.drop(index= 'Mean', inplace=True, axis=0) #dropping the row of means
f1_Rbar_Dev.insert(0, 'Fold', range(1,11)) #adding the fold column
f1_Rbar_sum = f1_Rbar_Dev.sum().rename('Sum')
f1_Rbar_sum['Fold'] = '_'
f1_Rbar_Dev = pd.concat([f1_Rbar_Dev, f1_Rbar_sum.to_frame().T])
print('\n\n F1 Score Squared Deviation Table')
print('\n', f1_Rbar_Dev)

f1_denominator = (f1_Rbar_sum['LR'] + f1_Rbar_sum['RF'] + f1_Rbar_sum['SVM']) / (n *(k-1))
print(f"\nF1 Denominator: {f1_denominator}")

 F1 Score Squared Deviation Table

     Fold   LR    RF  SVM
0      1  1.0   1.0  0.0
1      2  1.0   1.0  0.0
2      3  1.0   1.0  0.0
3      4  1.0   1.0  0.0
4      5  1.0   1.0  0.0
5      6  0.0   1.0  1.0
6      7  1.0   1.0  0.0
7      8  1.0   1.0  0.0
8      9  1.0   1.0  0.0
9     10  0.0   1.0  1.0
Sum    _  8.0  10.0  2.0

F1 Denominator: 1.0

In [23]:
#The final equation - F1 Score
f1_Fried = f1_numerator / f1_denominator
print(f"Friedman Statistic for F1 Measure: {f1_Fried:.2f}")

Friedman Statistic for F1 Measure: 16.80

### Friedman Test for Training Time

In [24]:
print(f"The average score for the Training time of each algorithm: {time_rankMean}")

The average score for the Training time of each algorithm: Fold      _
LR      1.0
RF      3.0
SVM     2.0
Name: Mean, dtype: object

In [25]:
#Calculating the Numerator - Training time
trainTime_numerator = n * (((time_rankMean['LR'] - R_bar)**2) + ((time_rankMean['RF']-R_bar)**2) + ((time_rankMean['SVM']-R_bar)**2))
print(f"Time Numerator: {trainTime_numerator}")

Time Numerator: 20.0

In [26]:
#Calculating the Denominator - Training Time
time_Rbar_Dev = (time_ranks[model_cols] - R_bar)**2 #Calculating R - R_BAR for each cell
time_Rbar_Dev.drop(index= 'Mean', inplace=True, axis=0) #drop the row of means
time_Rbar_Dev.insert(0, 'Fold', range(1,11)) #adding the fold column
time_Rbar_sum = time_Rbar_Dev.sum().rename('Sum')
time_Rbar_sum['Fold'] = '_'
time_Rbar_Dev = pd.concat([time_Rbar_Dev, time_Rbar_sum.to_frame().T])
print('\n\n Training Time Squared Deviation Table')
print('\n', time_Rbar_Dev)

time_denominator = (time_Rbar_sum['LR'] + time_Rbar_sum['RF'] + time_Rbar_sum['SVM']) / (n *(k-1))
print(f"\nF1 Time Denominator: {time_denominator}")

 Training Time Squared Deviation Table

     Fold    LR    RF  SVM
0      1   1.0   1.0  0.0
1      2   1.0   1.0  0.0
2      3   1.0   1.0  0.0
3      4   1.0   1.0  0.0
4      5   1.0   1.0  0.0
5      6   1.0   1.0  0.0
6      7   1.0   1.0  0.0
7      8   1.0   1.0  0.0
8      9   1.0   1.0  0.0
9     10   1.0   1.0  0.0
Sum    _  10.0  10.0  0.0

F1 Time Denominator: 1.0

In [27]:
#The final equation - Training Time
time_Fried = trainTime_numerator / time_denominator
print(f"Friedman Statistic for Training time is: {time_Fried:.2f}")

Friedman Statistic for Training time is: 20.00

# Nemenyi Test

In [28]:
#Criticial Difference is given as CD = q * SQRT[k(k+1)/6n]
#Where q is the q-value at alpha α = 0.05 and k = 3 which is 2.343

q = 2.343   # for alpha=0.05, k=3
cd = q * (np.sqrt(k * (k + 1) / (6 * n)))

print(f'Critical Difference(CD) = {cd:.2f}')

Critical Difference(CD) = 1.05

#### Accuracy

In [29]:
print(f"The average for the Accuracy of each algorithm: \n{Accuracy_rankMean}")
print(f"\nLR vs RF: |{Accuracy_rankMean['LR']} - {Accuracy_rankMean['RF']}| = {abs(Accuracy_rankMean['LR'] - Accuracy_rankMean['RF']):.2f}")
print(f"LR vs SVM:|{Accuracy_rankMean['LR']} - {Accuracy_rankMean['SVM']}| = {abs(Accuracy_rankMean['LR'] - Accuracy_rankMean['SVM']):.2f}")
print(f"RF vs SVM:|{Accuracy_rankMean['RF']} - {Accuracy_rankMean['SVM']}| = {abs(Accuracy_rankMean['LR'] - Accuracy_rankMean['RF']):.2f}")

The average for the Accuracy of each algorithm:
Fold      _
LR      2.8
RF      1.0
SVM     2.2
Name: Mean, dtype: object

LR vs RF: |2.8 - 1.0| = 1.80
LR vs SVM:|2.8 - 2.2| = 0.60
RF vs SVM:|1.0 - 2.2| = 1.80

#### F1 Score

In [30]:
print(f"The average score for the F1 Measure of each algorithm: \n{F1_rankMean}")
print(f"\nLR vs RF: |{F1_rankMean['LR']} - {F1_rankMean['RF']}| = {abs(F1_rankMean['LR'] - F1_rankMean['RF']):.2f}")
print(f"LR vs SVM:|{F1_rankMean['LR']} - {F1_rankMean['SVM']}| = {abs(F1_rankMean['LR'] - F1_rankMean['SVM']):.2f}")
print(f"RF vs SVM:|{F1_rankMean['RF']} - {F1_rankMean['SVM']}| = {abs(F1_rankMean['LR'] - F1_rankMean['RF']):.2f}")

The average score for the F1 Measure of each algorithm:
Fold      _
LR      2.8
RF      1.0
SVM     2.2
Name: Mean, dtype: object

LR vs RF: |2.8 - 1.0| = 1.80
LR vs SVM:|2.8 - 2.2| = 0.60
RF vs SVM:|1.0 - 2.2| = 1.80

#### Training Time

In [31]:
print(f"The average score for the Training time of each algorithm: {time_rankMean}")
print(f"\nLR vs RF: |{time_rankMean['LR']} - {time_rankMean['RF']}| = {abs(time_rankMean['LR'] - time_rankMean['RF']):.2f}")
print(f"LR vs SVM:|{time_rankMean['LR']} - {time_rankMean['SVM']}| = {abs(time_rankMean['LR'] - time_rankMean['SVM']):.2f}")
print(f"RF vs SVM:|{time_rankMean['RF']} - {time_rankMean['SVM']}| = {abs(time_rankMean['LR'] - time_rankMean['RF']):.2f}")

The average score for the Training time of each algorithm: Fold      _
LR      1.0
RF      3.0
SVM     2.0
Name: Mean, dtype: object

LR vs RF: |1.0 - 3.0| = 2.00
LR vs SVM:|1.0 - 2.0| = 1.00
RF vs SVM:|3.0 - 2.0| = 2.00